/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function setEntry(url: string): void
export declare function setLastEntry(): void
export interface Entry {
  host: string
  path: string
  duration: number
  timestamp: number
}
export interface DailyAnalytics {
  date: string
  totalTimeSpent: number
  gameTimeSpent: number
}
export interface AnalyticsReport {
  entries: Array<Entry>
  totalTimeSpent: number
  totalGameTimeSpent: number
  timeSpentPerHost: Record<string, number>
  weekData: Array<DailyAnalytics>
}
export declare function getAllData(): AnalyticsReport
