/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function init(joinBtn: boolean, initialUrl: string): void
export declare function setStatus(url: string): void
