on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            targets: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
          - os: windows-latest
            targets: [x86_64-pc-windows-msvc, i686-pc-windows-msvc]
          - os: macos-latest
            targets: [x86_64-apple-darwin, aarch64-apple-darwin]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - id: get_version
        shell: bash
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - run: npm ci

      - uses: dtolnay/rust-toolchain@stable

      - shell: bash 
        run: |
          for target in ${{ join(matrix.targets, ' ') }}; do
            rustup target add "$target"
          done

      - if: matrix.os == 'ubuntu-latest'
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - if: matrix.os == 'ubuntu-latest'
        uses: docker/setup-buildx-action@v3

      - if: contains(matrix.targets, 'aarch64-unknown-linux-gnu') && matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            binutils-aarch64-linux-gnu \
            libc6-dev-arm64-cross

          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

      - if: contains(matrix.targets, 'aarch64-apple-darwin') && matrix.os == 'macos-latest'
        run: |
          echo "RUSTFLAGS=-C link-arg=-undefined -C link-arg=dynamic_lookup" >> $GITHUB_ENV

      - working-directory: ./src-rust
        shell: bash
        run: |
          npm install
          for target in ${{ join(matrix.targets, ' ') }}; do
            if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
              cd analytics && cross build --target "$target" --release && npx napi build --target "$target" --release --platform && cd ..
              cd drpc && cross build --target "$target" --release && npx napi build --target "$target" --release --platform && cd ..
            else
              cd analytics && cargo build --target "$target" --release && npx napi build --target "$target" --release --platform && cd ..
              cd drpc && cargo build --target "$target" --release && npx napi build --target "$target" --release --platform && cd ..
            fi
          done

      - uses: softprops/action-gh-release@v2.0.6
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}