on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            targets: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
          - os: windows-latest
            targets: [x86_64-pc-windows-msvc, i686-pc-windows-msvc]
          - os: macos-latest
            targets: [x86_64-apple-darwin, aarch64-apple-darwin]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - id: get_version
        shell: bash
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - shell: bash
        run: |
          tag="v${{ steps.get_version.outputs.version }}"
          if git show-ref --tags --verify --quiet "refs/tags/${tag}"; then
            echo "Tag ${tag} already exists."
            exit 1
          fi

      - run: npm i --ignore-scripts

      - uses: dtolnay/rust-toolchain@stable

      - shell: bash 
        run: |
          for target in ${{ join(matrix.targets, ' ') }}; do
            rustup target add "$target"
          done

      - if: matrix.os == 'ubuntu-latest'
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - if: contains(matrix.targets, 'aarch64-unknown-linux-gnu') # Ubuntu ARM64 only
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - if: contains(matrix.targets, 'aarch64-unknown-linux-gnu') # Ubuntu ARM64 only
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

      - if: contains(matrix.targets, 'aarch64-apple-darwin') # macOS ARM64 only
        run: echo "RUSTFLAGS=-C link-arg=-undefined -C link-arg=dynamic_lookup" >> $GITHUB_ENV

      - working-directory: ./src-rust
        shell: bash
        run: |
          for target in ${{ join(matrix.targets, ' ') }}; do
              cd analytics && npx napi build --target "$target" --release --platform --js false
              cd ../drpc && npx napi build --target "$target" --release --platform --js false
              cd ..
          done

      - uses: softprops/action-gh-release@v2.0.6
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}