name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          # Linux targets (using cross)
          - os: ubuntu-latest
            rust_target: x86_64-unknown-linux-gnu
            node_abi: linux-x64-gnu
            electron_arch: x64
            artifacts: "*.AppImage *.tar.gz *.zip"
            use_cross: true
          - os: ubuntu-latest
            rust_target: aarch64-unknown-linux-gnu
            node_abi: linux-arm64
            electron_arch: arm64
            artifacts: "*.AppImage *.tar.gz *.zip"
            use_cross: true
            
          # Windows targets (native)
          - os: windows-latest
            rust_target: x86_64-pc-windows-msvc
            node_abi: win32-x64-msvc
            electron_arch: x64
            artifacts: "*.exe *.blockmap *.zip"
            use_cross: false
          - os: windows-latest
            rust_target: i686-pc-windows-msvc
            node_abi: win32-ia32-msvc
            electron_arch: ia32
            artifacts: "*.exe *.blockmap *.zip"
            use_cross: false
            
          # macOS targets (native)
          - os: macos-latest
            rust_target: x86_64-apple-darwin
            node_abi: darwin-x64
            electron_arch: x64
            artifacts: "*.dmg *.zip"
            use_cross: false
          - os: macos-latest
            rust_target: aarch64-apple-darwin
            node_abi: darwin-arm64
            electron_arch: arm64
            artifacts: "*.dmg *.zip"
            use_cross: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - id: get_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - run: npm ci

      # Setup Rust
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add ${{ matrix.rust_target }}

      # Setup cross only for Linux targets
      - name: Install cross
        if: matrix.use_cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - name: Setup Docker
        if: matrix.use_cross
        uses: docker/setup-buildx-action@v3

      - name: Install cross-compilation toolchain
        if: matrix.os == 'ubuntu-latest' && matrix.rust_target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            binutils-aarch64-linux-gnu \
            libc6-dev-arm64-cross

          # Set correct linker
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

      - name: Setup macOS ARM64 build
        if: matrix.rust_target == 'aarch64-apple-darwin'
        run: |
          rustup target add aarch64-apple-darwin
          echo "RUSTFLAGS=-C link-arg=-undefined -C link-arg=dynamic_lookup" >> $GITHUB_ENV

      - working-directory: ./src-rust
        shell: bash
        run: |
          npm install
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            # Using cross for all steps
            cd analytics && cross build --target ${{ matrix.rust_target }} --release
            cd ../drpc && cross build --target ${{ matrix.rust_target }} --release
            cd ..
            
            # Build Node-API bindings using cross
            cd analytics && cross run --target ${{ matrix.rust_target }} -- napi build --target ${{ matrix.rust_target }} --release
            cd ../drpc && cross run --target ${{ matrix.rust_target }} -- napi build --target ${{ matrix.rust_target }} --release
          else
            # Native builds for Windows/macOS
            cd analytics && cargo build --target ${{ matrix.rust_target }} --release
            cd ../drpc && cargo build --target ${{ matrix.rust_target }} --release
            cd ..
            
            cd analytics && npx napi build --target ${{ matrix.rust_target }} --release
            cd ../drpc && npx napi build --target ${{ matrix.rust_target }} --release
          fi

      # Collect artifacts
      - shell: bash
        run: |
          mkdir -p "rust-plugins/${{ matrix.rust_target }}"
          find src-rust -name "*.node" -exec cp {} "rust-plugins/${{ matrix.rust_target }}" \;

      # Build Electron
      - run: npm install electron-builder --save-dev
      - run: npm run build
      - run: npx electron-builder --${{ matrix.os == 'macos-latest' && 'mac' || matrix.os == 'windows-latest' && 'win' || 'linux' }} --${{ matrix.electron_arch }}

      # Upload artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.rust_target }}
          path: |
            dist/${{ matrix.artifacts }}
            rust-plugins/${{ matrix.rust_target }}/*.node

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.build.outputs.version }}
          files: |
            artifacts/**/*