on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - id: get_version
        shell: bash
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - shell: bash
        run: |
          tag="v${{ steps.get_version.outputs.version }}"
          if git show-ref --tags --verify --quiet "refs/tags/${tag}"; then
            echo "Tag ${tag} already exists."
            exit 1
          fi

      - run: npm ci

      - uses: dtolnay/rust-toolchain@stable

      - working-directory: ./src-rust
        run: |
          cd analytics && npx napi build --release
          cd ../drpc && npx napi build --release

      - uses: softprops/action-gh-release@v2.0.6
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}